Added Windows relase and installation intructions in it's own markdown file.
ERPLibre/ERPLibre pull request #55
Opened 2023-02-02 18:31 UTC by castiel10k

2023-02-02 20:43 UTC, mathben requested changes

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +**"WSL2 Ubuntu 22.04" will be referred as "WSL2"**<br>
Il n'y a pas de <br> en markdown
https://www.markdownguide.org/basic-syntax

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +A guide on how to set up a work space and run ERPLibre in Windows.
workspace, un seul mot

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +# Windows release and development
Mentionné quel version de Windows est supporté dans ce guide.

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +make -j 2
je suggère : make -j $(nproc)
Ça va mettre le maximum de CPU

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +clone
clone? ça semble une erreur de frappe

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev rsync
Il semble manquer l'installation de postgres, il faudrait aussi postgis

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +sudo apt install make git
ça semble inutile de dire d'installer make ici s'il est utilisé dans le guide précédemment

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +make run
Je préfère suggérer d'utiliser `./run.sh`

2023-02-02 20:43 UTC, mathben commented on doc/WINDOWS_INSTALLATION.md
> +```
met un saut de ligne à la fin.
Format ce fichier avec l'outil markdown dans Pycharm.
Ajoute des images au besoin, crée un répertoire doc/image/
https://www.markdownguide.org/basic-syntax/#images

2023-02-02 21:24 UTC, castiel10k commented on doc/WINDOWS_INSTALLATION.md
> +# Windows release and development
Version minimal rajouter

2023-02-02 21:24 UTC, castiel10k commented on doc/WINDOWS_INSTALLATION.md
> +sudo apt install make git
typo de mes notes! woops

2023-02-02 21:24 UTC, castiel10k commented on doc/WINDOWS_INSTALLATION.md
> +clone
typo de mes notes! woops

2023-02-03 18:42 UTC, castiel10k commented on doc/WINDOWS_INSTALLATION.md
> +sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev rsync
Les installations ne sont pas manquantes, je crois qu'elle sont installer durant le "make install". Quand je roule les commandes pour debuter le service, postgres s'allume correctement.

2023-02-03 20:44 UTC, mathben approved these changes
Merci, belle contribution. Enlève src pour image svp.

2023-02-08 19:17 UTC, merged